name: 🚀 Deploy to ZimaBlade

on:
  push:
    branches: [ main ]
    paths:
      - 'index.html'
      - '.github/workflows/**'
      - 'deploy.yml'
      - 'Dockerfile'
      - 'favicon.png'
      - '**/*.css'
      - '**/*.js'
      - 'assets/**'
      - '!indexTestBed.html'

jobs:
  deploy:
    runs-on: self-hosted
    steps:

      # 1️⃣ Grab your code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Pull only safe files into helpdesk folder
      - name: Pull latest on local ZimaBlade (safe-only)
        run: |
          cd /home/casaos/helpdesk
          git fetch origin main
          git checkout origin/main -- index.html favicon.png Dockerfile assets/
          git clean -fd
